# Generated by Django 3.0.4 on 2020-03-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, default=1900)),
                ('date_watched', models.DateField()),
            ],
        ),
    ]
